import re
from snakebids import bids

from snakebids import set_bids_spec
set_bids_spec("v0_0_0")

configfile: 'config/config.yml'
    
include: 'rules/zipfiles.smk'
include: 'rules/atlas.smk'
include: 'rules/mrtproc.smk'
include: 'rules/fmri.smk'
include: 'rules/hippunfold.smk'
